### ISSUE TITLE
Error in whichLib.js on Windows 7 in NW.js

### ISSUE THREAD

**Issue by asanchezgomez** [stevenvachon/hidefile#1]
Hi!

I've got an error ("Uncaught error: File not found") in \hidefile\node_modules\winattr\lib\whichLib.js, on line 87. Your package works fine on Linux, but I've found this problem on Windows 7. I have hidefile version 1.1.0.

Best regards,
Alejandro.

**Comment by stevenvachon** [comment]
What version of nodejs ?

**Comment by asanchezgomez** [comment]
On Windows, I have v4.4.0 and on Linux v0.12.2.

**Comment by stevenvachon** [comment]
I cannot reproduce the issue.

**Comment by asanchezgomez** [comment]
It is in NW.js application on Windows, but it works fine on Linux...

**Comment by stevenvachon** [comment]
Perhaps nw.js has an issue with loading [fswin](https://npmjs.com/fswin) and/or other bindings?

**Comment by asanchezgomez** [comment]
Finally, I've seen that the problem could be the backslashes in Windows, since if you have the following:
`var newpath = hidefile.hideSync("path\to\file.ext");`
it would fail. Therefore, it is the user in my app selects a local path with a file browser in Windows, first I would have to replace "\" with "/" and then I could use hideSync. It is the best way to do it?

On the other hand, I don't understand why in Windows is necessary to have a prefixed file in order to be a hidden file, because I thought if a file called "users.txt" has "hidden" attribute, it would be a file hidden, independently if it is prefixed  or not.

Thanks for your effort!

**Comment by stevenvachon** [comment]
It's prefixed on Windows as well because, like Node.js, this library is Unix-first. The folder name remains consistent across all platforms. The file/folder is hidden, so whether it has a prefixed "." shouldn't matter to a Windows user.

**Comment by stevenvachon** [comment]
Node.js has no problem using "\" or "/" on Windows. The binding, however, may only work with "\". I'll have to test this.

**Comment by asanchezgomez** [comment]
Okey thank you very much for your answers! I understand your approach. Congratulations for your incredible work! :)

**Comment by asanchezgomez** [comment]
Hi @stevenvachon ! Have you tested this problem? I need a package for test if a file is hidden or not on both Windows and Linux, but on Windows I'm still having problems. I've tried with winattr library with the following codes:

**First code:**

```
var winattr = require('winattr');
var path = "C:\Users\pepe\Documents\hiddenFolder";
var attrs = winattr.getSync(path);
console.log(attrs.hidden);
```

**Second code:**

```
var winattr = require('winattr');
var path = "C:\\Users\\pepe\\Documents\\hiddenFolder";
var attrs = winattr.getSync(path);
console.log(attrs.hidden);
```

My path format on Windows is like in the first code, but getSync function throws an error. The second code works fine but I have to add manually double "\".  Other Node.js functions, like fs.readdirSync, works fine with the path of the first code.

Best regards.

**Comment by stevenvachon** [comment]
Your first path is incorrect even on Windows as it contains commenting/unicode characters.

``` js
console.log("C:\Unicode");  //-> "C:Unicode"
```

``` js
console.log("C:\Unicode\");
```

```
[eval]:1
console.log("C:\Unicode\")
            ^^^^^^^^^^^^^^
SyntaxError: Unexpected token ILLEGAL
    at Object.exports.runInThisContext (vm.js:53:16)
    at Object.<anonymous> ([eval]-wrapper:6:22)
    at Module._compile (module.js:541:32)
    at node.js:328:29
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

**Comment by asanchezgomez** [comment]
I'm currently testing it, and in Node.js works fine, but the problem comes when this package or winattr package is used in NW.js (I'm testing with 0.12.3 version). It throws randomly a "File not found" error in whichLib.js:87. Do you have any idea of this behaviour? I could give you an app example in order to test this error if you need it.

Best regards.

**Comment by stevenvachon** [comment]
You will always need to use `\\`.
